pipeline {
    agent {
        docker{
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparation'){
            steps {
                sh 'cd rocklov-v3 && cd api && bundle install'
            }
        }
        stage('Automatic testing') {
            steps {
                sh 'cd rocklov-v3 && cd api && rspec'
                junit 'rocklov-v3/api/logs/report.xml'
            }
        }
    }
}
