# frozen_string_literal: true

source "https://rubygems.org"

gem 'cucumber', '5.2' # Essa gem vai executar os cenários através da sintax do gherkin que são os cenários em BDD.
gem 'capybara', '3.33' # Essa gem é para automatizar testes para aplicação web simulando o comportamento de um usuário.
gem 'selenium-webdriver', '3.142.7' # Essa gem serve para abrir o navegador.
gem 'rspec', '3.9' # Essa gem serve para fazer algumas validações na automação web.
gem 'faker', '2.14' # Essa gem serve para criar dados fakes. Usamos ela para gerar emails aleatórios.
gem 'mongo', '2.13.1'
