pipeline {
    agent {
        docker{
            image 'pethersonerasmo/ruby-web-agent'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparation'){
            steps {
                sh 'cd rocklov-v3 && cd web && bundle install'
            }
        }
        stage('Automatic testing') {
            steps {
                sh 'cd rocklov-v3 && cd web && rake local_seed'
            }
        }
        stage('UAT') {
            steps{
                echo 'Aguardando testes de aceitação.'
                input message: 'Podemos ir para produção?'
            }
        }
        stage('Producao') {
            steps {
                echo 'WEBApp pronta para produção :D'
            }
        }
    }
    post {
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'rocklov-v3/web/logs']]
        }
    }
}
