---
# Neste arquivo configuramos as URL que usamos para gerar os teste no ambiente de homologação, caso queira rodar os arquivos no alocal usamos o arquivo local.yml
url: http:teste.com.br
mongo: mongodb://usuario@senha:200.234.55.77:27017/rocklov
